---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# This is for my Analsys Training Questions v2024

(Adapted from the [the associated document](https://docs.google.com/document/d/1854ZftQ1oNE_W-WQkklmbln-9bRQrnSTOq7AlmGLWcU/edit#heading=h.jdt8ay97uqg7))

This repo is meant to be for doing some of the training analyes. 


## Setup

### Creating a new repo from template

1. Create new repo with template by going to [the repo in GitHub](https://github.com/GlobalFishingWatch/research-r-template) and clicking the `Use this template` button. You can also use the GitHub command line tool, `gh repo create --template https://github.com/GlobalFishingWatch/research-r-template.git` option. More documentation on this library is available [here](https://cli.github.com/manual/gh_repo_create).
2. Rename `research-r-template.Rproj` to your project name. The convention is to name it the same as your repo.
3. Update the `README.md` to what is relevant for your project.


## Structure and descriptions

To learn more about this structure and how it is meant to be used throughout different stages of the project, see [this presentation](https://docs.google.com/presentation/d/1E51s4VhcLzCwN_v_yeOpaGLtNEF5fcZanlO1lRsmGiw/edit?usp=sharing).

    |- README.md		<- Top-level README on how to use this repo
    |- data			    <- Data files. Create subfolders as necessary.
    |- docs			    <- Documentation.
    |- models		    <- Trained models, model summaries, etc.
    |- notebooks 	    <- Jupyter notebooks and R markdown. Naming convention TBD. Use jupytext to convert
    |				       to .py before committing and do not commit the notebook itself. Suggest having
    |				       subfolders for different subsets of analysis. Could also have different
    |				       subfolders for each person if that makes more sense for your project/team.
    |- outputs		    <- Models results, static reports, etc. Create  additional subfolders as necessary.
    |    |- figures	    <- Create versioned figures folders if desired.
    |- queries		    <- SQL files (.sql, .jinja2, etc). Create subfolders as necessary. When creating
    |				       new tables in BigQuery, be sure to use a schema with good field descriptions.
    |- scripts		    <- Regular python and R files. These may use code from <module> but are not
    |				       notebooks. A good place for scripts that run data pipelines, train models, etc.
    |- .gitignore	    <- Modify as necessary.
    
